on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $
      - uses: actions/setup-node@v1
        with:
          node-version:
            $
      - name: Install Dependencies
        if:
          steps.cache-nodemodules.outputs.cache-hit != 'true'
            #
        run:
          npm ci
      - name: Build
        run: npm run build -- --prod
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test -- --prod
